// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application'

import AutoSubmitController from './auto_submit_controller'
import PageTransitionMissingController from './page_transition_missing_controller'
import TransitionController from './transition_controller'
import VideoPlayerController from './video_player_controller'

application.register('auto-submit', AutoSubmitController)
application.register('page-transition-missing', PageTransitionMissingController)
application.register('transition', TransitionController)
application.register('video-player', VideoPlayerController)
